### ISSUE TITLE
An error occurs when trying to transfer data from the  GoogleSheets Source to two  GoogleSheets Destinations with the same config

### ISSUE THREAD

**Issue by SerhiiSpivak** [conduitio-labs/conduit-connector-google-sheets#42]
### Bug description

The user creates the GoogleSheets Source connector and two GoogleSheets Destinations with the same config; then the user starts the pipeline -> the system returns an error

```
2022-09-26T17:48:34+00:00 ERR pipeline stopped error="node d6d5d8df-4832-4eca-a600-7edcc03b8277-acker stopped with error: failed to receive ack: error receiving ack: unable to marshal the record: unexpected end of JSON input" component=pipeline.Service pipeline_id=a1119aba-4258-484c-9c51-38e900816f75 stack=[{"file":"/home/serhiispivak/go/src/github.com/ConduitIO/conduit-main/pkg/pipeline/lifecycle.go","func":"[github.com/conduitio/conduit/pkg/pipeline.(*Service](http://github.com/conduitio/conduit/pkg/pipeline.(*Service)).runPipeline.func1","line":411},{"file":"/home/serhiispivak/go/src/github.com/ConduitIO/conduit-main/pkg/pipeline/stream/destination_acker.go","func":"[github.com/conduitio/conduit/pkg/pipeline/stream.(*DestinationAckerNode](http://github.com/conduitio/conduit/pkg/pipeline/stream.(*DestinationAckerNode)).worker","line":131},{"file":"/home/serhiispivak/go/src/github.com/ConduitIO/conduit-main/pkg/connector/destination.go","func":"[github.com/conduitio/conduit/pkg/connector.(*destination](http://github.com/conduitio/conduit/pkg/connector.(*destination)).Ack","line":247},{"file":"/home/serhiispivak/go/src/github.com/ConduitIO/conduit-main/pkg/plugin/standalone/v1/destination.go","func":"[github.com/conduitio/conduit/pkg/plugin/standalone/v1.(*destinationPluginClient](http://github.com/conduitio/conduit/pkg/plugin/standalone/v1.(*destinationPluginClient)).Ack","line":119}] 2022-09-26T17:48:35+00:00 INF request processed duration=0.007612 grpc_method=/api.v1.PipelineService/GetPipeline grpc_status_code=OK http_endpoint="GET /v1/pipelines/a1119aba-4258-484c-9c51-38e900816f75" request_id=6cda8027-a449-4895-a5cc-417f8401898
```

### Steps to reproduce

1. Create Pipeline
2. Create GoogleSheets Source connector and two GoogleSheets Destinations with the same config (see below config):
```yaml
version: 1.0                  

pipelines:                    
  pipeline1:                   
    status: stopped             
    name: pipeline1             
    description: desc           
    connectors:                 
      con1:                 
        type: source            
        plugin: standalone:google-sheets  
        name: googlesheet-source            
        settings:              
          credentialsFile: <path://to/credential/file>
          tokensFile: <path://to/token/file>
          sheetsURL: <URL of the google spreadshee>
          dateTimeRenderOption:
          valueRenderOption:
          pollingPeriod:
      con2:
        type: destination
        plugin: standalone:google-sheets
        name: googlesheet-DESTINATION
        settings:
           credentialsFile: <path://to/credential/file>
           tokensFile: <path://to/token/file>
           sheetsURL: <URL of the google spreadshee>
           sheetName: test_sheet_1
           valueInputOption:
           maxRetries:
      con3:
        type: destination
        plugin: standalone:google-sheets
        name: googlesheet-DESTINATION
        settings:
           credentialsFile: <path://to/credential/file>
           tokensFile: <path://to/token/file>
           sheetsURL: <URL of the google spreadshee>
           sheetName: test_sheet_1
           valueInputOption:
           maxRetries:
```
3. Start the pipeline
4. Get an error

```
2022-09-26T17:48:34+00:00 ERR pipeline stopped error="node d6d5d8df-4832-4eca-a600-7edcc03b8277-acker stopped with error: failed to receive ack: error receiving ack: unable to marshal the record: unexpected end of JSON input" component=pipeline.Service pipeline_id=a1119aba-4258-484c-9c51-38e900816f75 stack=[{"file":"/home/serhiispivak/go/src/github.com/ConduitIO/conduit-main/pkg/pipeline/lifecycle.go","func":"[github.com/conduitio/conduit/pkg/pipeline.(*Service](http://github.com/conduitio/conduit/pkg/pipeline.(*Service)).runPipeline.func1","line":411},{"file":"/home/serhiispivak/go/src/github.com/ConduitIO/conduit-main/pkg/pipeline/stream/destination_acker.go","func":"[github.com/conduitio/conduit/pkg/pipeline/stream.(*DestinationAckerNode](http://github.com/conduitio/conduit/pkg/pipeline/stream.(*DestinationAckerNode)).worker","line":131},{"file":"/home/serhiispivak/go/src/github.com/ConduitIO/conduit-main/pkg/connector/destination.go","func":"[github.com/conduitio/conduit/pkg/connector.(*destination](http://github.com/conduitio/conduit/pkg/connector.(*destination)).Ack","line":247},{"file":"/home/serhiispivak/go/src/github.com/ConduitIO/conduit-main/pkg/plugin/standalone/v1/destination.go","func":"[github.com/conduitio/conduit/pkg/plugin/standalone/v1.(*destinationPluginClient](http://github.com/conduitio/conduit/pkg/plugin/standalone/v1.(*destinationPluginClient)).Ack","line":119}] 2022-09-26T17:48:35+00:00 INF request processed duration=0.007612 grpc_method=/api.v1.PipelineService/GetPipeline grpc_status_code=OK http_endpoint="GET /v1/pipelines/a1119aba-4258-484c-9c51-38e900816f75" request_id=6cda8027-a449-4895-a5cc-417f8401898
```

### Version

v0.3.0-nightly.20220927
