### ISSUE TITLE
Not stable issue: Sometimes data from GoogleSheets Source isn't recorded (updated, deleted ) to the Destination if the data was added during the pause and then re-starting the pipeline 

### ISSUE THREAD

**Issue by SerhiiSpivak** [conduitio-labs/conduit-connector-google-sheets#44]
### Bug description

Sometimes data from GoogleSheets Source isn't recorded (updated, deleted ) to the Destination (for example NATS PubSub) if the data was added during the pause and then re-starting the pipeline

**Not stable issue**

### Steps to reproduce

1. Create Pipeline
2. Create GoogleSheets Source connector and NATS PubSub Destination (see below config):
```yaml
version: 1.0                  

pipelines:                    
  pipeline1:                   
    status: stopped             
    name: pipeline1             
    description: desc           
    connectors:                 
      con1:                 
        type: source            
        plugin: standalone:google-sheets  
        name: googlesheet-source-sheet            
        settings:              
          credentialsFile: <path://to/credential/file>
          tokensFile: <path://to/token/file>
          sheetsURL: <URL of the google spreadsheet>
          dateTimeRenderOption:
          valueRenderOption:
          pollingPeriod:
      con2:
        type: destination
        plugin: standalone:nats-pubsub
        name: nats-pubsub-DESTINATION
        settings:
           urls: <NATS connection URL> 
           subject: sbj
           connectionName:
           nkeyPath:
           credentialsFilePath:
           tls.clientCertPath:
           tls.clientPrivateKeyPath:
           tls.rootCACertPath:
           maxReconnects:
           reconnectWait:
```
3. Start the pipeline -> data is transferred to the Destination
4. Stop the pipeline 
5. Add (or update, remove) data in GoogleSheets Source table
6. Re-start the pipeline 
7. Data isn't recorded (updated, deleted ) to the Destination

### Version

v0.3.0-nightly.20220927
